<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><OutputType>WinExe</OutputType><AssemblyName>DanbooruTagTool</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../DanbooruTagTool.Core/DanbooruTagTool.Core.csproj"/><ProjectReference Include="../DanbooruTagTool.Data/DanbooruTagTool.Data.csproj"/></ItemGroup></Project>
