from __future__ import annotations

import csv
from pathlib import Path

QUEUE = Path("docs/issue70/audit/EXTERNAL_QUEUE_LIVE.csv")
OUT = Path("docs/issue70/audit/external_resolution_copyright_official_batch076.csv")

ITEMS = {'nier_(series)': {'verdict': 'FIX_BOTH',
                   'display': 'NieRシリーズ',
                   'search': 'NieR | ニーア | ニーアシリーズ',
                   'url': 'https://www.jp.square-enix.com/nierautomata/',
                   'note': 'Square Enix uses the official NieR brand spelling; the umbrella row should retain series context.'},
 'lucky_star': {'verdict': 'KEEP',
                'display': '',
                'search': '',
                'url': 'https://store.kadokawa.co.jp/shop/series/series00150701',
                'note': 'KADOKAWA uses the Japanese title らき☆すた.'},
 'cho_kaguya-hime!': {'verdict': 'FIX_DISPLAY',
                      'display': '超かぐや姫！',
                      'search': '',
                      'url': 'https://www.netflix.com/jp/title/81756595',
                      'note': 'Netflix official Japanese title uses 超かぐや姫！ with full-width punctuation.'},
 'umineko_no_naku_koro_ni': {'verdict': 'KEEP',
                             'display': '',
                             'search': '',
                             'url': 'https://www.umine.co/about/world/',
                             'note': 'Official series site uses うみねこのなく頃に.'},
 'super_smash_bros.': {'verdict': 'FIX_BOTH',
                       'display': '大乱闘スマッシュブラザーズ',
                       'search': 'スマブラ | スマッシュブラザーズ',
                       'url': 'https://www.smashbros.com/ja_JP/products/',
                       'note': 'Nintendo official Japanese series/product naming uses 大乱闘スマッシュブラザーズ.'},
 'heaven_burns_red': {'verdict': 'FIX_BOTH',
                      'display': 'ヘブンバーンズレッド',
                      'search': 'ヘブバン',
                      'url': 'https://heaven-burns-red.com/',
                      'note': 'Official site lists title ヘブンバーンズレッド.'},
 'oshi_no_ko': {'verdict': 'KEEP',
                'display': '',
                'search': '',
                'url': 'https://ichigoproduction.com/Season3/',
                'note': 'Official anime site uses 【推しの子】.'},
 'undertale': {'verdict': 'FIX_BOTH',
               'display': 'UNDERTALE',
               'search': 'アンダーテール',
               'url': 'https://undertale.jp/',
               'note': 'Japanese official site uses UNDERTALE as title.'},
 'steins;gate': {'verdict': 'FIX_BOTH',
                 'display': 'STEINS;GATE',
                 'search': 'シュタインズ・ゲート | シュタインズゲート',
                 'url': 'https://steinsgate.jp/',
                 'note': 'Official site lists title STEINS;GATE (シュタインズ・ゲート).'},
 'a.i._voice': {'verdict': 'FIX_BOTH',
                'display': 'A.I.VOICE',
                'search': 'アイボス',
                'url': 'https://aivoice.jp/',
                'note': 'Official product site uses A.I.VOICE and identifies アイボス as a nickname.'},
 'panty_&_stocking_with_garterbelt': {'verdict': 'FIX_BOTH',
                                      'display': 'Panty & Stocking with Garterbelt',
                                      'search': 'パンティ＆ストッキングwithガーターベルト | パンスト',
                                      'url': 'https://newpsg.com/',
                                      'note': 'Official franchise materials use Panty & Stocking with Garterbelt; Japanese full rendering and nickname are search aliases.'},
 'street_fighter_6': {'verdict': 'FIX_BOTH',
                      'display': 'ストリートファイター6',
                      'search': 'スト6',
                      'url': 'https://www.streetfighter.com/6/ja-jp/',
                      'note': 'Official Capcom title is ストリートファイター6.'},
 'kobayashi-san_chi_no_maidragon': {'verdict': 'FIX_BOTH',
                                    'display': '小林さんちのメイドラゴン',
                                    'search': 'メイドラゴン',
                                    'url': 'https://maidragon.jp/',
                                    'note': 'Official anime portal uses 小林さんちのメイドラゴン.'},
 'aikatsu!_(series)': {'verdict': 'FIX_BOTH',
                       'display': 'アイカツ！',
                       'search': 'アイカツ | アイカツ！シリーズ',
                       'url': 'https://www.aikatsu.net/',
                       'note': 'Official portal uses アイカツ！ branding.'},
 'love_live!_superstar!!': {'verdict': 'FIX_BOTH',
                            'display': 'ラブライブ！スーパースター!!',
                            'search': 'ラブライブ スーパースター',
                            'url': 'https://www.lovelive-anime.jp/yuigaoka/',
                            'note': 'Official franchise title is ラブライブ！スーパースター!!.'},
 'twisted_wonderland': {'verdict': 'FIX_BOTH',
                        'display': 'ディズニー ツイステッドワンダーランド',
                        'search': 'ツイステ',
                        'url': 'https://www.disney.co.jp/games/dtw',
                        'note': 'Disney official page uses ディズニー ツイステッドワンダーランド.'},
 'gundam_gquuuuuux': {'verdict': 'FIX_BOTH',
                      'display': '機動戦士Gundam GQuuuuuuX',
                      'search': '機動戦士ガンダム ジークアクス | ジークアクス',
                      'url': 'https://gundam-official.com/gquuuuuux/',
                      'note': 'Official Gundam site uses 機動戦士Gundam GQuuuuuuX.'},
 'the_hundred_line_-last_defense_academy-': {'verdict': 'FIX_BOTH',
                                             'display': 'HUNDRED LINE -最終防衛学園-',
                                             'search': 'ハンドラ',
                                             'url': 'https://hundred-line.com/',
                                             'note': 'Official site lists HUNDRED LINE -最終防衛学園-.'},
 'synthesizer_v': {'verdict': 'FIX_BOTH',
                   'display': 'Synthesizer V',
                   'search': 'シンセサイザーV | Synthesizer V Studio',
                   'url': 'https://dreamtonics.com/ja/synthesizerv/',
                   'note': 'Dreamtonics official branding uses Synthesizer V.'},
 'devil_may_cry_(series)': {'verdict': 'FIX_BOTH',
                            'display': 'デビル メイ クライ',
                            'search': 'デビルメイクライ | Devil May Cry | DMC',
                            'url': 'https://www.capcom.co.jp/devilmaycry/',
                            'note': 'Capcom official Japanese branding uses デビル メイ クライ.'},
 'atelier_ryza': {'verdict': 'FIX_BOTH',
                  'display': 'ライザのアトリエ ～常闇の女王と秘密の隠れ家～',
                  'search': 'ライザのアトリエ',
                  'url': 'https://ar-anime.com/',
                  'note': 'Official anime/product title preserves the full subtitle.'},
 'the_legend_of_zelda:_ocarina_of_time': {'verdict': 'FIX_DISPLAY',
                                          'display': 'ゼルダの伝説 時のオカリナ',
                                          'search': '',
                                          'url': 'https://www.nintendo.com/jp/titles/20010000013227.html',
                                          'note': 'Nintendo official title is ゼルダの伝説 時のオカリナ.'},
 "yu-gi-oh!_5d's": {'verdict': 'FIX_DISPLAY',
                      'display': "遊☆戯☆王5D's",
                      'search': '',
                      'url': 'https://www.konami.com/yugioh/duel_links/legendarydecks/ja/5ds01',
                      'note': "Konami official page uses 遊☆戯☆王5D's."},
 'fire_emblem_echoes:_shadows_of_valentia': {'verdict': 'FIX_BOTH',
                                              'display': 'ファイアーエムブレム Echoes もうひとりの英雄王',
                                              'search': 'ファイアーエムブレムEchoes',
                                              'url': 'https://www.nintendo.com/jp/hardware/amiibo/game/ajjj/index.html',
                                              'note': 'Nintendo official title includes もうひとりの英雄王.'},
 'tokyo_ghoul': {'verdict': 'FIX_BOTH',
                 'display': '東京喰種トーキョーグール',
                 'search': '東京喰種 | トーキョーグール',
                 'url': 'https://www.marv.jp/special/tokyoghoul/first/story_1st.html',
                 'note': 'Official anime site uses 東京喰種トーキョーグール.'},
 'umamusume:_cinderella_gray': {'verdict': 'FIX_DISPLAY',
                                'display': 'ウマ娘 シンデレラグレイ',
                                'search': '',
                                'url': 'https://anime-cinderellagray.com/intro/',
                                'note': 'Official anime title uses a space between ウマ娘 and シンデレラグレイ.'},
 'senran_kagura_new_link': {'verdict': 'FIX_BOTH',
                            'display': 'シノビマスター 閃乱カグラ NEW LINK',
                            'search': 'シノマス',
                            'url': 'https://hpgames.jp/shinomas/',
                            'note': 'Official site uses シノビマスター 閃乱カグラ NEW LINK.'},
 'wonderful_precure!': {'verdict': 'FIX_DISPLAY',
                        'display': 'わんだふるぷりきゅあ！',
                        'search': '',
                        'url': 'https://www.toei-anim.co.jp/tv/wonderful_precure/',
                        'note': 'Toei official title uses わんだふるぷりきゅあ！.'},
 '22/7': {'verdict': 'FIX_BOTH',
          'display': '22/7',
          'search': 'ナナニジ | ナナブンノニジュウニ',
          'url': 'https://nanabunnonijyuuni.com/',
          'note': 'Official brand surface is 22/7; nickname belongs in search.'},
 'kanon': {'verdict': 'FIX_BOTH',
           'display': 'Kanon',
           'search': 'カノン',
           'url': 'https://key.visualarts.gr.jp/product/kanon/',
           'note': 'Key official product title is Kanon.'},
 'mihoyo': {'verdict': 'FIX_BOTH',
            'display': 'miHoYo',
            'search': 'ミホヨ',
            'url': 'https://www.hoyoverse.com/ja-jp/about-us',
            'note': 'Japanese-facing corporate material uses the Latin brand/company identity rather than Chinese characters.'},
 'go!_princess_precure': {'verdict': 'FIX_DISPLAY',
                          'display': 'Go！プリンセスプリキュア',
                          'search': '',
                          'url': 'https://www.toei-anim.co.jp/tv/princess_precure/',
                          'note': 'Toei official Japanese title is Go！プリンセスプリキュア.'},
 'komi-san_wa_komyushou_desu': {'verdict': 'FIX_DISPLAY',
                                'display': '古見さんは、コミュ症です。',
                                'search': '',
                                'url': 'https://komisan-official.com/',
                                'note': 'Official anime title includes the final punctuation.'},
 'final_fantasy_vii:_advent_children': {'verdict': 'FIX_BOTH',
                                        'display': 'FINAL FANTASY VII ADVENT CHILDREN',
                                        'search': 'アドベントチルドレン | FF7AC',
                                        'url': 'https://www.jp.square-enix.com/ffviiacc/',
                                        'note': 'Square Enix official branding uses FINAL FANTASY VII ADVENT CHILDREN.'},
 'inuyasha': {'verdict': 'KEEP',
              'display': '',
              'search': '',
              'url': 'https://www.ytv.co.jp/inuyasha/',
              'note': '犬夜叉 is the official Japanese title.'},
 'ikkitousen': {'verdict': 'KEEP',
                'display': '',
                'search': '',
                'url': 'https://ikkitousen.com/',
                'note': 'Official franchise site uses 一騎当千 / 真・一騎当千 branding.'},
 'oshiro_project:re': {'verdict': 'FIX_BOTH',
                       'display': '御城プロジェクト:RE',
                       'search': '城プロRE | 城プロ',
                       'url': 'https://oshirore-dmmgames.com/',
                       'note': 'Official site uses 御城プロジェクト：RE ～CASTLE DEFENSE～; concise product name retained.'},
 'make_heroine_ga_oo_sugiru!': {'verdict': 'FIX_BOTH',
                                'display': '負けヒロインが多すぎる！',
                                'search': 'マケイン',
                                'url': 'https://makeine-anime.com/',
                                'note': 'Official anime site uses 負けヒロインが多すぎる！ and calls characters マケイン.'},
 'kimi_no_koto_ga_dai_dai_dai_dai_daisuki_na_100-nin_no_kanojo': {'verdict': 'FIX_BOTH',
                                                                    'display': '君のことが大大大大大好きな100人の彼女',
                                                                    'search': '100カノ',
                                                                    'url': 'https://hyakkano.com/',
                                                                    'note': 'Official title is 君のことが大大大大大好きな100人の彼女.'},
 'yes!_precure_5': {'verdict': 'FIX_DISPLAY',
                    'display': 'Yes！プリキュア5',
                    'search': '',
                    'url': 'https://www.toei-anim.co.jp/tv/startwinkle_precure/',
                    'note': 'Toei archive listing preserves the official Yes！プリキュア5 title.'},
 'magical_mirai_(vocaloid)': {'verdict': 'FIX_BOTH',
                              'display': '初音ミク「マジカルミライ」',
                              'search': 'マジカルミライ',
                              'url': 'https://magicalmirai.com/',
                              'note': 'Official portal brands the event as 初音ミク「マジカルミライ」.'},
 'happinesscharge_precure!': {'verdict': 'FIX_DISPLAY',
                              'display': 'ハピネスチャージプリキュア！',
                              'search': '',
                              'url': 'https://www.toei-anim.co.jp/tv/happinesscharge_precure/',
                              'note': 'Official Toei title includes the final exclamation mark.'},
 'promare': {'verdict': 'KEEP',
             'display': '',
             'search': '',
             'url': 'https://promare-movie.com/',
             'note': 'Official film site uses プロメア.'},
 'blue_lock': {'verdict': 'KEEP',
               'display': '',
               'search': '',
               'url': 'https://tv.bluelock-pr.com/',
               'note': 'Official anime site uses ブルーロック.'},
 'poptepipic': {'verdict': 'FIX_DISPLAY',
                'display': 'ポプテピピック',
                'search': '',
                'url': 'https://hoshiiro.jp/',
                'note': 'Official anime franchise title is ポプテピピック, not a season-specific label.'},
 'gundam_zz': {'verdict': 'FIX_DISPLAY',
               'display': '機動戦士ガンダムΖΖ',
               'search': '',
               'url': 'https://www.gundam.info/',
               'note': 'Official Gundam title is 機動戦士ガンダムΖΖ.'},
 'working!!': {'verdict': 'KEEP',
               'display': '',
               'search': '',
               'url': 'https://www.wagnaria.com/',
               'note': 'Official anime site uses WORKING!! / WORKING!!!; canonical row corresponds to WORKING!! identity.'},
 'dragon_ball_(classic)': {'verdict': 'KEEP',
                           'display': '',
                           'search': '',
                           'url': 'https://dragon-ball-official.com/',
                           'note': 'Official franchise site uses ドラゴンボール.'},
 'my_melody_(series)': {'verdict': 'KEEP',
                        'display': '',
                        'search': '',
                        'url': 'https://www.sanrio.co.jp/characters/mymelody/',
                        'note': 'Sanrio official character name is マイメロディ.'},
 'mob_psycho_100': {'verdict': 'KEEP',
                    'display': '',
                    'search': '',
                    'url': 'https://mobpsycho100.com/',
                    'note': 'Official anime title is モブサイコ100.'},
 'tales_of_the_abyss': {'verdict': 'FIX_BOTH',
                        'display': 'テイルズ オブ ジ アビス',
                        'search': 'アビス',
                        'url': 'https://toa20th.tales-ch.jp/',
                        'note': 'Official series product title is テイルズ オブ ジ アビス.'},
 'rune_factory': {'verdict': 'FIX_BOTH',
                  'display': 'ルーンファクトリー',
                  'search': 'ルンファク',
                  'url': 'https://www.marv.jp/special/game/runefactory/',
                  'note': 'Official franchise title is ルーンファクトリー.'},
 'hachigatsu_no_cinderella_nine': {'verdict': 'FIX_BOTH',
                                   'display': '八月のシンデレラナイン',
                                   'search': 'ハチナイ',
                                   'url': 'https://lp.hachinai.com/',
                                   'note': 'Official game title is 八月のシンデレラナイン.'},
 'saenai_heroine_no_sodatekata': {'verdict': 'FIX_BOTH',
                                  'display': '冴えない彼女の育てかた',
                                  'search': '冴えカノ',
                                  'url': 'https://www.saenai.tv/',
                                  'note': 'Official anime site uses 冴えない彼女の育てかた.'},
 'watashi_ni_tenshi_ga_maiorita!': {'verdict': 'FIX_BOTH',
                                     'display': '私に天使が舞い降りた！',
                                     'search': 'わたてん',
                                     'url': 'https://watatentv.com/',
                                     'note': 'Official anime/franchise title is 私に天使が舞い降りた！.'},
 'uzaki-chan_wa_asobitai!': {'verdict': 'FIX_DISPLAY',
                             'display': '宇崎ちゃんは遊びたい！',
                             'search': '',
                             'url': 'https://uzakichan.com/',
                             'note': 'Official title includes the final exclamation mark.'},
 'star_twinkle_precure': {'verdict': 'FIX_BOTH',
                          'display': 'スター☆トゥインクルプリキュア',
                          'search': 'スタプリ',
                          'url': 'https://www.toei-anim.co.jp/tv/startwinkle_precure/',
                          'note': 'Toei official title is スター☆トゥインクルプリキュア.'},
 'microsoft_windows': {'verdict': 'FIX_BOTH',
                       'display': 'Windows',
                       'search': 'Microsoft Windows | マイクロソフトWindows',
                       'url': 'https://support.microsoft.com/ja-jp/windows/',
                       'note': 'Microsoft Japanese support consistently uses Windows as the product surface.'},
 'mahou_tsukai_no_yoru': {'verdict': 'FIX_BOTH',
                          'display': '魔法使いの夜',
                          'search': 'まほよ',
                          'url': 'https://mahoyo-movie.com/',
                          'note': 'Official TYPE-MOON/ufotable site uses 魔法使いの夜.'},
 'dolphin_wave': {'verdict': 'FIX_BOTH',
                  'display': 'ドルフィンウェーブ',
                  'search': 'ドルウェブ',
                  'url': 'https://hpgames.jp/dolphin-wave/',
                  'note': 'Official product title is ドルフィンウェーブ.'},
 'mabinogi': {'verdict': 'KEEP',
              'display': '',
              'search': '',
              'url': 'https://mabinogi.nexon.co.jp/',
              'note': 'Official Japanese site uses マビノギ.'},
 'coca-cola': {'verdict': 'FIX_BOTH',
               'display': 'コカ･コーラ',
               'search': 'コカコーラ | Coca-Cola',
               'url': 'https://www.coca-cola.com/jp/ja/brands/coca-cola',
               'note': 'Official Japanese brand spelling uses コカ･コーラ.'},
 'ghost_in_the_shell': {'verdict': 'KEEP',
                        'display': '',
                        'search': '',
                        'url': 'https://www.theghostintheshell-anime.jp/',
                        'note': 'Official Japanese franchise identity uses 攻殻機動隊.'},
 'godzilla_(series)': {'verdict': 'KEEP',
                       'display': '',
                       'search': '',
                       'url': 'https://godzilla.com/',
                       'note': 'Official franchise identity is ゴジラ / Godzilla.'},
 'steins;gate_0': {'verdict': 'FIX_BOTH',
                   'display': 'STEINS;GATE 0',
                   'search': 'シュタインズ・ゲート ゼロ | シュタインズゲートゼロ',
                   'url': 'https://steinsgate.jp/',
                   'note': 'Official series portal lists STEINS;GATE 0.'},
 'mega_man_battle_network_(series)': {'verdict': 'KEEP',
                                      'display': '',
                                      'search': '',
                                      'url': 'https://www.capcom-games.com/megaman/exe/ja-jp/',
                                      'note': 'Capcom Japanese branding uses ロックマンエグゼ.'},
 'castlevania_(series)': {'verdict': 'KEEP',
                          'display': '',
                          'search': '',
                          'url': 'https://www.konami.com/games/castlevania/',
                          'note': 'Konami Japanese franchise is established as 悪魔城ドラキュラ.'},
 'show_by_rock!!': {'verdict': 'KEEP',
                    'display': '',
                    'search': '',
                    'url': 'https://showbyrock.com/',
                    'note': 'Official franchise title is SHOW BY ROCK!!.'},
 'duel_masters': {'verdict': 'KEEP',
                  'display': '',
                  'search': '',
                  'url': 'https://dm.takaratomy.co.jp/',
                  'note': 'Takara Tomy official title is デュエル・マスターズ.'},
 'ryuu_ga_gotoku_(series)': {'verdict': 'KEEP',
                              'display': '',
                              'search': '',
                              'url': 'https://ryu-ga-gotoku.com/',
                              'note': 'SEGA official portal uses 龍が如く.'},
 'air_(visual_novel)': {'verdict': 'KEEP',
                        'display': '',
                        'search': '',
                        'url': 'https://key.visualarts.gr.jp/product/air/',
                        'note': 'Key official product title is AIR.'},
 'resident_evil_4_(remake)': {'verdict': 'KEEP',
                              'display': '',
                              'search': '',
                              'url': 'https://www.residentevil.com/re4/ja-jp/',
                              'note': 'Capcom Japanese official title is バイオハザード RE:4.'},
 'tears_of_themis': {'verdict': 'KEEP',
                     'display': '',
                     'search': '',
                     'url': 'https://tot.hoyoverse.com/ja-jp/',
                     'note': 'HoYoverse Japanese official title is 未定事件簿.'},
 'snk': {'verdict': 'KEEP',
         'display': '',
         'search': '',
         'url': 'https://www.snk-corp.co.jp/',
         'note': 'Official company/brand surface is SNK.'},
 'grisaia_(series)': {'verdict': 'KEEP',
                      'display': '',
                      'search': '',
                      'url': 'https://grisaia-pt.com/',
                      'note': 'Official franchise branding uses グリザイア.'},
 'tokimeki_memorial': {'verdict': 'KEEP',
                        'display': '',
                        'search': '',
                        'url': 'https://www.konami.com/games/tokimeki/',
                        'note': 'Konami official franchise title is ときめきメモリアル.'},
 'octopath_traveler': {'verdict': 'KEEP',
                       'display': '',
                       'search': '',
                       'url': 'https://www.jp.square-enix.com/octopathtraveler/',
                       'note': 'Square Enix official Japanese page uses オクトパストラベラー.'},
 'tokyo_7th_sisters': {'verdict': 'KEEP',
                       'display': '',
                       'search': '',
                       'url': 'https://t7s.jp/',
                       'note': 'Official title is Tokyo 7th シスターズ.'},
 'blue_archive_the_animation': {'verdict': 'KEEP',
                                'display': '',
                                'search': '',
                                'url': 'https://sh-anime.shochiku.co.jp/bluearchive-anime/',
                                'note': 'Official anime title is ブルーアーカイブ The Animation.'},
 'gridman_universe_(movie)': {'verdict': 'KEEP',
                              'display': '',
                              'search': '',
                              'url': 'https://ssss-movie.net/',
                              'note': 'Official film title is グリッドマン ユニバース.'}}

FIELDS = [
    "row_id","canonical_tag","post_count","display_ja","search_ja",
    "prior_audit_verdict","audit_verdict","proposed_display_ja","proposed_search_ja",
    "reason_code","confidence","evidence_refs","audit_note","approval_status"
]

def main() -> None:
    with QUEUE.open(encoding="utf-8-sig", newline="") as f:
        queue = list(csv.DictReader(f))
    by_tag = {r["canonical_tag"]: r for r in queue}

    missing = sorted(set(ITEMS) - set(by_tag))
    assert not missing, f"batch076 targets not unresolved anymore: {missing}"

    rows = []
    for tag, spec in ITEMS.items():
        q = by_tag[tag]
        assert q["category"] == "Copyright", (tag, q["category"])
        verdict = spec["verdict"]
        pd = spec["display"] if verdict in {"FIX_DISPLAY","FIX_BOTH"} else ""
        ps = spec["search"] if verdict in {"FIX_SEARCH","FIX_BOTH"} else ""
        if verdict in {"FIX_DISPLAY","FIX_BOTH"}:
            assert pd and pd != q["display_ja"], (tag, q["display_ja"], pd)
        if verdict == "FIX_BOTH":
            assert ps, tag
        rows.append({
            "row_id": q["row_id"],
            "canonical_tag": tag,
            "post_count": q["post_count"],
            "display_ja": q["display_ja"],
            "search_ja": q["search_ja"],
            "prior_audit_verdict": "NEEDS_EXTERNAL_CHECK",
            "audit_verdict": verdict,
            "proposed_display_ja": pd,
            "proposed_search_ja": ps,
            "reason_code": "OFFICIAL_OR_FIRST_PARTY_TITLE_CONFIRMED_BATCH076",
            "confidence": "HIGH",
            "evidence_refs": spec["url"],
            "audit_note": spec["note"],
            "approval_status": "PROPOSED",
        })

    assert len(rows) == 80
    assert len({r["row_id"] for r in rows}) == 80
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(rows)
    print({"rows": len(rows), "output": str(OUT)})

if __name__ == "__main__":
    main()
